#
# To see original grafana.ini
#   docker run --rm --entrypoint /bin/sh grafana/grafana:11.5.2 -c "cat /etc/grafana/grafana.ini"
#


#################################### Server ####################################
[server]
# Protocol (http, https, h2, socket)
protocol = http

# The http port to use
http_port = 8080


#################################### Logging ##########################
[log]
# Either "console", "file", "syslog". Default is console and  file
# Use space to separate multiple modes, e.g. "console file"
;mode = console file

# Either "debug", "info", "warn", "error", "critical", default is "info"
level = info


#################################### Security ####################################
[security]
# default admin user, created on startup
admin_user = example

# default admin email, created on startup
admin_email = example@devel.org

# default admin password, can be changed before first start of grafana, or in profile settings
admin_password = $__file{/run/secrets/GF_SECURITY_ADMIN_PASSWORD}

################################## Feature Management ##############################################
[feature_management]
hidden_toggles =
read_only_toggles =


#################################### Anonymous Auth ######################
[auth.anonymous]
#enabled = true
enabled = false
org_name = "Devel"
org_role = Viewer
hide_version = true
